In [21]:
import numpy as np 
import matplotlib.pyplot as pt 
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv("datasets/train.csv").as_matrix()
print(data)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [22]:
# training dataset
clf = DecisionTreeClassifier()
xtrain = data[0:21000, 1:]
train_label = data[0:21000, 0]

clf.fit(xtrain, train_label)

# testing data
xtest = data[21000:, 1:]
actual_label = data[21000:, 0]

# d = xtest[10]
# d.shape = (28,28)
# pt.imshow(d-255, cmap='gray')
# print(clf.predict([xtest[10]]))
# pt.show()

p = clf.predict(xtest)

count = 0
for i in range(0,21000):
    count +=1 if p[i] == actual_label[i] else 0
    
print("Accuracy = ", (count/21000)*100)

Accuracy =  83.52857142857142
